---
ID: "7d0a413c-c00e-49dc-a64d-b9f703333645"
Parent: "b807828b-670b-4b3a-83f0-04df159791b4"
Template: "b807828b-670b-4b3a-83f0-04df159791b4"
Path: /sitecore/templates/Feature/Media/_HasMediaImage/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180712T105612Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
