---
ID: "28f9e378-eae8-4b5d-92fa-988c92bf13aa"
Parent: "ef556019-1706-4d3c-93d7-a56b903c5130"
Template: "ef556019-1706-4d3c-93d7-a56b903c5130"
Path: /sitecore/templates/Feature/Media/_HasMediaSelector/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180712T105619Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
