---
ID: "8dadb781-a9e1-48dc-b8e9-97e30bedaa36"
Parent: "3c45af40-8ac0-4124-a665-de37306f74ee"
Template: "3c45af40-8ac0-4124-a665-de37306f74ee"
Path: /sitecore/templates/Feature/Media/_HasMedia/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180712T105418Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
